#POST http://localhost:7071/api/FormRec
POST http://customskillsfunc.azurewebsites.net/api/FormRec

{
    "values": [
      {
        "recordId": "a1",
        "data":
           {
             "url": "https://g7storage.blob.core.windows.net/all-forms/Insurance%20Form%2007.pdf",
              "sas": "?st=2019-10-24T09%3A21%3A08Z&se=2019-10-25T09%3A21%3A08Z&sp=rl&sv=2018-03-28&sr=c&sig=rEwSIlrn0aO2DP0aQ1LQkUpCE74P3Cw1W3BG8TDy7Kk%3D"
           }
      }
    ]
}